# Generated by Django 2.1.2 on 2019-01-21 17:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', verbose_name='Полное описание вопроса'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата решистрации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Время создания вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Доступность вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True, verbose_name='Полное описание вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок ярлыка'),
        ),
    ]
